---
- name: Restart corosync
  become: true
  ansible.builtin.systemd_service:
    name: corosync
    state: restarted

- name: Restart pacemaker
  become: true
  ansible.builtin.systemd_service:
    name: pacemaker
    state: restarted
