$ANSIBLE_VAULT;1.1;AES256
38633035353565383664383366666430323136353232386635363332663838653839386338386566
3031656639613965666338356334383461326663303962330a303631323962386366616261383232
66343132366334643562326635313538316462336330383335393232666631336665653665323132
3061613730363130320a333635623166333634373231623736666336663739393862343262636166
65306132336430616238623866656234663161653465656466356430636563303032356130333038
6564656330616261336633303464643434373963363632363065
